apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-db
  namespace: default
  labels:
    app: patient-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-db
  template:
    metadata:
      labels:
        app: patient-db
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: patient-db-secret
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: patient-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: patient-db-secret
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: patient-db
      volumes:
        - name: patient-db
          persistentVolumeClaim:
            claimName: patient-db-pv-claim