apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-database
  namespace: default
  labels:
    app: patient-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-database
  template:
    metadata:
      labels:
        app: patient-database
    spec:
      containers:
        - name: postgres
          image: postgres:12
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: patient-database-secret
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: patient-database-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: patient-database-secret
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: patient-database
            - mountPath: docker-entrypoint-initdb.d
              name: initdb
              readOnly: true
      volumes:
        - name: patient-database
          persistentVolumeClaim:
            claimName: patient-database-pv-claim
        - name: initdb
          configMap:
            name: patient-database-initdb
