kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: patient-database-pv-claim
  labels:
    app: patient-database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi