kind: PersistentVolume
apiVersion: v1
metadata:
  name: patient-database-pv-volume
  labels:
    type: local
    app: patient-database
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"