kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: patient-db-pv-claim
  labels:
    app: patient-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi